#!/usr/bin/env bash
#writes the fizzbuzz from 1 to 100
number=1

while [ "$number" -le 100 ]
do
    if [ $((number % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((number % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((number % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$number"
    fi

    number=$((number + 1))
done
