#!/usr/bin/env bash
#tells a story ussing passwd info
while IFS=: read -r username password userid groupid user_info home shell
do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
