#!/usr/bin/env bash
#writes best school ten times but on the ninth writes hi
count=1
while [ "$count -le 10 ]
do
  echo "Best School"

  if [ "$count -eq 9 ]
  then
     echo "Hi"
  fi

  count=$((count + 1))
done

